import { useEffect, useState } from 'react'
import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom'
import Sidebar from './components/Sidebar'
import Topbar from './components/Topbar'
import { apiError, createInstrument, createTest, getAlerts, getAudit, getHealth, getInstruments, getReports, getTests, login } from './services/api'
import Login from './pages/Login'
import Dashboard from './pages/Dashboard'
import Instruments from './pages/Instruments'
import NewInstrument from './pages/NewInstrument'
import Tests from './pages/Tests'
import NewTest from './pages/NewTest'
import TestExecution from './pages/TestExecution'
import Reports from './pages/Reports'
import VerifyReport from './pages/VerifyReport'
import Alerts from './pages/Alerts'
import AuditLogs from './pages/AuditLogs'
import SensorSimulator from './pages/SensorSimulator'
import CameraOCR from './pages/CameraOCR'
import './App.css'
import './theme.css'
export default function App() { const [loggedIn,setLoggedIn]=useState(()=>Boolean(localStorage.getItem('novanexus-token'))); const [data,setData]=useState({instruments:[],tests:[],reports:[],alerts:[],audit:[]}); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [health,setHealth]=useState({api:false,database:false}); const [mobileOpen,setMobileOpen]=useState(false); const loadData=async()=>{setLoading(true);setError('');try{const [instruments,tests,reports,alerts,audit]=await Promise.all([getInstruments(),getTests(),getReports(),getAlerts(),getAudit()]);setData({instruments,tests,reports,alerts,audit})}catch(err){setError(apiError(err))}finally{setLoading(false)}}; useEffect(()=>{const unauthorize=()=>setLoggedIn(false);window.addEventListener('novanexus-unauthorized',unauthorize);if(loggedIn){loadData();getHealth().then(value=>setHealth({api:value.status==='ok',database:value.database!==false})).catch(()=>setHealth({api:false,database:false}))}return()=>window.removeEventListener('novanexus-unauthorized',unauthorize)},[loggedIn]); const addInstrument=async item=>{const result=await createInstrument(item);await loadData();return result}; const addTest=async item=>{const result=await createTest(item);await loadData();return result}; if(!loggedIn)return <Login onLogin={async credentials=>{const result=await login(credentials);localStorage.setItem('novanexus-token',result.token);localStorage.setItem('novanexus-user',JSON.stringify(result.user));setLoggedIn(true)}}/>; return <BrowserRouter><div className="app-shell"><Sidebar open={mobileOpen} onClose={()=>setMobileOpen(false)} alertCount={data.alerts.length}/><main className="main-shell"><Topbar onMenu={()=>setMobileOpen(true)} data={data}/><Routes><Route path="/" element={<Dashboard data={data} loading={loading} error={error} health={health} onRetry={loadData}/>} /><Route path="/instruments" element={<Instruments data={data} loading={loading} error={error} onRetry={loadData}/>} /><Route path="/new-instrument" element={<NewInstrument onAdd={addInstrument}/>} /><Route path="/tests" element={<Tests data={data} loading={loading} error={error} onRetry={loadData}/>} /><Route path="/new-test" element={<NewTest data={data} onAdd={addTest}/>} /><Route path="/execution" element={<TestExecution data={data} onAdd={addTest}/>} /><Route path="/reports" element={<Reports data={data} loading={loading} error={error} onGenerated={loadData}/>} /><Route path="/verify" element={<VerifyReport data={data}/>} /><Route path="/alerts" element={<Alerts data={data} loading={loading} error={error}/>} /><Route path="/audit" element={<AuditLogs data={data} loading={loading} error={error}/>} /><Route path="/simulator" element={<SensorSimulator/>}/><Route path="/camera" element={<CameraOCR data={data}/>} /><Route path="*" element={<Navigate to="/" replace/>}/></Routes></main></div></BrowserRouter> }
