import { Router } from 'express'
import db,{audit} from '../database/db.js'
import {evaluateReading,evaluateTest} from '../services/ruleEngine.js'
const router=Router(); const getTest=id=>db.prepare('SELECT t.*,i.manufacturer,i.model,i.capacity FROM tests t JOIN instruments i ON i.id=t.instrument_id WHERE t.id=?').get(id)
router.get('/',(req,res)=>res.json(db.prepare('SELECT * FROM tests ORDER BY created_at DESC').all()))
router.post('/',(req,res)=>{try{const b=req.body||{};if(!b.instrumentId||!b.testType)return res.status(400).json({error:'instrumentId and testType are required'});if(!db.prepare('SELECT id FROM instruments WHERE id=?').get(b.instrumentId))return res.status(404).json({error:'Instrument not found'});const id=b.id||`TST-${Date.now()}`;db.prepare('INSERT INTO tests (id,instrument_id,test_type,temperature,humidity,tester_id,remarks) VALUES (?,?,?,?,?,?,?)').run(id,b.instrumentId,b.testType,b.temperature??null,b.humidity??null,req.user.id,b.remarks||null);audit(req.user.id,'test creation',id,`${b.testType} for ${b.instrumentId}`);res.status(201).json(getTest(id))}catch(e){res.status(500).json({error:e.message})}})
router.get('/:id',(req,res)=>{const test=getTest(req.params.id);if(!test)return res.status(404).json({error:'Test not found'});test.readings=db.prepare('SELECT * FROM test_readings WHERE test_id=? ORDER BY id').all(req.params.id);res.json(test)})
router.post('/:id/readings',(req,res)=>{try{if(!getTest(req.params.id))return res.status(404).json({error:'Test not found'});const b=req.body||{}, evaluated=evaluateReading(b);const info={...b,...evaluated};db.prepare('INSERT INTO test_readings (test_id,test_point,reference_value,indicated_value,permissible_error,error,absolute_error,result,source) VALUES (?,?,?,?,?,?,?,?,?)').run(req.params.id,b.testPoint||String(Date.now()),b.referenceValue,b.indicatedValue,b.permissibleError,info.error,info.absoluteError,info.result,b.source||'MANUAL');audit(req.user.id,'reading creation',req.params.id,`Point ${b.testPoint||'new'} evaluated ${info.result}`);res.status(201).json(info)}catch(e){res.status(400).json({error:e.message})}})
router.post('/:id/evaluate',(req,res)=>{try{if(!getTest(req.params.id))return res.status(404).json({error:'Test not found'});const readings=db.prepare('SELECT * FROM test_readings WHERE test_id=?').all(req.params.id);const result=evaluateTest(readings);db.prepare('UPDATE tests SET result=?,status=? WHERE id=?').run(result,'COMPLETED',req.params.id);audit(req.user.id,'evaluation',req.params.id,`Result: ${result}`);res.json({testId:req.params.id,result,readings,note:'OIML R76-based configurable evaluation.'})}catch(e){res.status(500).json({error:e.message})}})
export default router
