import axios from 'axios'

export const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:4000/api'
export const api = axios.create({ baseURL: API_URL, headers: { 'Content-Type': 'application/json' } })
api.interceptors.request.use((config) => { const token = localStorage.getItem('novanexus-token'); if (token) config.headers.Authorization = `Bearer ${token}`; return config })
api.interceptors.response.use((response) => response, (error) => { if (error.response?.status === 401) { localStorage.removeItem('novanexus-token'); localStorage.removeItem('novanexus-auth'); window.dispatchEvent(new Event('novanexus-unauthorized')) } return Promise.reject(error) })
export const apiError = (error) => error.response?.data?.error || (error.request ? 'Unable to connect to NovaNexus server.' : error.message)
export const getHealth = () => api.get('/health').then((r) => r.data)
export const login = (credentials) => api.post('/auth/login', credentials).then((r) => r.data)
export const getInstruments = () => api.get('/instruments').then((r) => r.data.map((item) => ({ ...item, serial: item.serialNumber || item.serial_number, interval: item.verificationScaleInterval || item.verification_scale_interval, accuracy: item.accuracyClass || item.accuracy_class, health: item.status === 'ACTIVE' ? 'HEALTHY' : item.status })))
export const createInstrument = (item) => api.post('/instruments', { ...item, serialNumber: item.serialNumber || item.serial, verificationScaleInterval: item.verificationScaleInterval || item.interval, accuracyClass: item.accuracyClass || item.accuracy }).then((r) => r.data)
export const getTests = () => api.get('/tests').then((r) => r.data.map((item) => ({ ...item, instrument: item.instrument_id || item.instrumentId, type: item.test_type || item.testType, tester: item.tester || 'Authenticated tester', date: item.created_at ? new Date(item.created_at).toLocaleDateString() : 'Today' })))
export const createTest = (item) => api.post('/tests', item).then((r) => r.data)
export const getTest = (id) => api.get(`/tests/${id}`).then((r) => r.data)
export const addReading = (id, reading) => api.post(`/tests/${id}/readings`, reading).then((r) => r.data)
export const evaluateTest = (id) => api.post(`/tests/${id}/evaluate`).then((r) => r.data)
export const getReports = () => api.get('/reports').then((r) => r.data)
export const generateReport = (testId) => api.post(`/reports/${testId}/generate`).then((r) => r.data)
export const getReport = (id) => api.get(`/reports/${id}`).then((r) => r.data)
export const verifyReport = (id) => api.post(`/reports/${id}/verify`).then((r) => r.data)
export const downloadReport = (id) => api.get(`/reports/${id}/pdf`, { responseType: 'blob' }).then((r) => r.data)
export const getAlerts = () => api.get('/alerts').then((r) => r.data.map((item) => ({ ...item, text: item.message })))
export const getAudit = () => api.get('/audit').then((r) => r.data)
export const generateSensorReading = (values = {}) => api.post('/sensors/readings', values).then((r) => r.data)
